version: '3.6'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ../mysqldata/codept:/var/lib/mysql
      - ./backup:/home
    ports:
      - 3306:3306
networks:
  default:
    external:
      name: codept