version: '3.6'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/:/var/www/
      - ./dev.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/cert.pem:/etc/nginx/conf.d/cert.pem
      - ./ssl/key.pem:/etc/nginx/conf.d/key.pem
  api:
    build: ./apidocker
    volumes:
      - ./api/api:/api
      - ./.env:/src/.env
      - ./log:/log:Z
    env_file:
      .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOST: db
      PMA_ABSOLUTE_URI: http://test.local
networks:
  default:
    external:
      name: codept